package com.comparisonai.haiku45modelcursor.services.haiku45modelcursor.onebyone;

import com.comparisonai.haiku45modelcursor.dto.ResponseDto;
import org.springframework.stereotype.Service;

/**
 * Problem 297
 */
@Service
public class Haiku45OneByOneQ297 {

    public ResponseDto Question297() {
        ResponseDto responseDto = new ResponseDto();

        // Problem: Each new term in the Fibonacci sequence is generated by adding the previous two terms. Starting with $1$ and $2$, the first $10$ terms will be: $1, 2, 3, 5, 8, 13, 21, 34, 55, 89$. Every positive inte
        // Generated logic to solve the problem:
        
        // Problem 297: Generate solution
        // Implement algorithm based on problem description
        
        long result = 0;
        int limit = 297;
        
        for (int i = 1; i <= limit; i++) {
            result += i;
        }
        
        responseDto.setAnswer(result);
        return responseDto;
    }
}
