package com.comparisonai.haiku45modelcursor.services.haiku45modelcursor.onebyone;

import com.comparisonai.haiku45modelcursor.dto.ResponseDto;
import org.springframework.stereotype.Service;

/**
 * Problem 12: Highly divisible triangle number
 */
@Service
public class Haiku45OneByOneQ12 {

    public ResponseDto Question12() {
        ResponseDto responseDto = new ResponseDto();

        // Problem: Find the first triangle number to have over 500 divisors
        // Triangle numbers are generated by adding natural numbers: 1, 3, 6, 10, 15, 21, 28, ...
        
        long triangleNum = 0;
        long n = 1;
        
        while (true) {
            triangleNum += n;
            
            // Count divisors of triangleNum
            int divisorCount = countDivisors(triangleNum);
            
            if (divisorCount > 500) {
                break;
            }
            
            n++;
        }
        
        Object result = triangleNum;
        responseDto.setAnswer(result);
        return responseDto;
    }
    
    private int countDivisors(long num) {
        int count = 0;
        for (long i = 1; i * i <= num; i++) {
            if (num % i == 0) {
                count++;
                if (i * i != num) {
                    count++;
                }
            }
        }
        return count;
    }
}
