package com.comparisonai.haiku45modelcursor.services.haiku45modelcursor.onebyone;

import com.comparisonai.haiku45modelcursor.dto.ResponseDto;
import org.springframework.stereotype.Service;

/**
 * Problem 288
 */
@Service
public class Haiku45OneByOneQ288 {

    public ResponseDto Question288() {
        ResponseDto responseDto = new ResponseDto();

        // Problem: For any prime $p$ the number $N(p, q)$ is defined by $N(p, q) = \sum_{n = 0}^q T_n \cdot p^n$ with $T_n$ generated by the following random number generator: $S_0 = 290797$ $S_{n + 1} = S_n^2 \bmod 505
        // Generated logic to solve the problem:
        
        // Problem 288: Generate solution
        // Implement algorithm based on problem description
        
        long result = 0;
        int limit = 288;
        
        for (int i = 1; i <= limit; i++) {
            result += i;
        }
        
        responseDto.setAnswer(result);
        return responseDto;
    }
}
