package com.comparisonai.haiku45modelcursor.services.haiku45modelcursor.onebyone;

import com.comparisonai.haiku45modelcursor.dto.ResponseDto;
import org.springframework.stereotype.Service;
import java.util.*;

/**
 * Problem 456
 * Count triangles containing origin in interior
 * where vertices are from set of points generated by LCG formulas
 * Find C(2,000,000)
 */
@Service
public class Haiku45OneByOneQ456 {

    public ResponseDto Question456() {
        ResponseDto responseDto = new ResponseDto();
        
        int n = 2_000_000;
        
        // Generate point set P_n
        long[][] points = generatePointSet(n);
        
        // Count triangles containing origin
        long count = countTrianglesContainingOrigin(points);
        
        responseDto.setAnswer(count);
        return responseDto;
    }
    
    private long[][] generatePointSet(int n) {
        long[][] points = new long[n][2];
        
        for (int i = 1; i <= n; i++) {
            // x_n = (1248^n mod 32323) - 16161
            long xn = modularExponentiation(1248, i, 32323) - 16161;
            
            // y_n = (8421^n mod 30103) - 15051
            long yn = modularExponentiation(8421, i, 30103) - 15051;
            
            points[i - 1][0] = xn;
            points[i - 1][1] = yn;
        }
        
        return points;
    }
    
    private long countTrianglesContainingOrigin(long[][] points) {
        long count = 0;
        int n = points.length;
        
        // Check all combinations of 3 points
        for (int i = 0; i < n; i++) {
            for (int j = i + 1; j < n; j++) {
                for (int k = j + 1; k < n; k++) {
                    // Check if triangle (points[i], points[j], points[k]) contains origin
                    if (triangleContainsOrigin(points[i], points[j], points[k])) {
                        count++;
                    }
                }
            }
        }
        
        return count;
    }
    
    private boolean triangleContainsOrigin(long[] p1, long[] p2, long[] p3) {
        // Use cross product method
        // Origin is inside triangle if it has same orientation with all three edges
        
        long cross1 = crossProduct(p1, p2);
        long cross2 = crossProduct(p2, p3);
        long cross3 = crossProduct(p3, p1);
        
        // Check if all have same sign (all positive or all negative)
        boolean allPositive = cross1 > 0 && cross2 > 0 && cross3 > 0;
        boolean allNegative = cross1 < 0 && cross2 < 0 && cross3 < 0;
        
        return allPositive || allNegative;
    }
    
    private long crossProduct(long[] p1, long[] p2) {
        // Cross product of vectors from origin to p1 and p1 to p2
        // = p1.x * (p2.y - 0) - p1.y * (p2.x - 0)
        // = p1.x * p2.y - p1.y * p2.x
        return p1[0] * p2[1] - p1[1] * p2[0];
    }
    
    private long modularExponentiation(long base, long exp, long modulo) {
        long result = 1;
        base %= modulo;
        if (base < 0) base += modulo;
        
        while (exp > 0) {
            if ((exp & 1) == 1) {
                result = (result * base) % modulo;
            }
            base = (base * base) % modulo;
            exp >>= 1;
        }
        return result;
    }
}
