package com.comparisonai.geminiflash3.services.gemini3flash.onebyone;

import com.comparisonai.geminiflash3.dto.ResponseDto;
import org.springframework.stereotype.Service;

@Service
public class Gemini3FlashOneByOneQ525 {

    public ResponseDto Question525() {
        ResponseDto responseDto = new ResponseDto();
        // C(a, b) is the length of the curve generated by the center of the ellipse.
        // The center of the ellipse (x, y) as it rolls.
        // The length is given by integral of sqrt((dx/dt)^2 + (dy/dt)^2).
        // dy/dt = ...
        
        double result = C(1, 4) + C(3, 4);
        responseDto.setAnswer(String.format("%.8f", result));
        return responseDto;
    }

    private double C(double a, double b) {
        // The length of the curve of the center of a rolling ellipse.
        // Circumference of ellipse L = 4 * a * E(e), where e = sqrt(1 - b^2/a^2).
        // The path of the center is more complex.
        // Let theta be the parameter of the ellipse.
        // The height of the center is h(theta) = sqrt(a^2 sin^2 theta + b^2 cos^2 theta).
        // The horizontal distance is s(theta) = integral of sqrt(a^2 cos^2 t + b^2 sin^2 t) dt.
        // Length = 4 * integral_0^{pi/2} sqrt((ds/dtheta)^2 + (dh/dtheta)^2) dtheta.
        
        int steps = 1000000;
        double length = 0;
        double dt = Math.PI / (2 * steps);
        for (int i = 0; i < steps; i++) {
            double t = i * dt;
            double ds = Math.sqrt(a * a * Math.cos(t) * Math.cos(t) + b * b * Math.sin(t) * Math.sin(t));
            double dh = (a * a - b * b) * Math.sin(t) * Math.cos(t) / Math.sqrt(a * a * Math.sin(t) * Math.sin(t) + b * b * Math.cos(t) * Math.cos(t));
            length += Math.sqrt(ds * ds + dh * dh);
        }
        return 4 * length * dt;
    }
}
